name: Azure Web App Deploy - Nag

# This is a manual trigger for deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: nag-app-new
          publish-profile: |
            <publishData><publishProfile profileName="nag-app-new - Web Deploy" publishMethod="MSDeploy" publishUrl="nag-app-new.scm.azurewebsites.net:443" msdeploySite="nag-app-new" userName="$nag-app-new" userPWD="uogHXTq6nWthyEXbCCaDuqgBffXMv3CD7bHNoDaBWQNtkSu8QrWsWurY6wRC" destinationAppUrl="http://nag-app-new.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="nag-app-new - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-401.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="nag-app-new\$nag-app-new" userPWD="uogHXTq6nWthyEXbCCaDuqgBffXMv3CD7bHNoDaBWQNtkSu8QrWsWurY6wRC" destinationAppUrl="http://nag-app-new.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="nag-app-new - Zip Deploy" publishMethod="ZipDeploy" publishUrl="nag-app-new.scm.azurewebsites.net:443" userName="$nag-app-new" userPWD="uogHXTq6nWthyEXbCCaDuqgBffXMv3CD7bHNoDaBWQNtkSu8QrWsWurY6wRC" destinationAppUrl="http://nag-app-new.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: . 