name: Azure Web App Deploy - Nag

on:
  push:
    branches:
      - main  # or use "master" if your main branch is named that

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create startup command file
        run: |
          echo "gunicorn --bind=0.0.0.0 --timeout 600 main:app" > startup.sh
          chmod +x startup.sh

      - name: Create deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" -x "*.venv*" -x "*.env*" -x "*.pyc" -x "__pycache__/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: nag-app-new
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip 